[build]
  publish = "mobile-web"
  functions = "netlify/functions"

[[redirects]]
  from = "/set-meetings"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/scout-schedules"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact-reminder"
  to = "/index.html"
  status = 200
