export const CALL_TRACKER_VERCEL_CONTRACT = {
  contract: 'prospect-call-tracker',
  version: 3,
  generatedFrom: 'src/domain/call-tracker-vercel-contract.ts',
  purpose:
    'Single Vercel-readable Call Tracker contract. The browser reads one event feed plus one optional summary helper; reporting counts come from explicit countsAsDial, countsAsContact, countsAsMeetingSet, countsAsPostMeetingOutcome, and counts_as_* booleans, never from activity_kind alone.',
  browserContract: {
    eventFeed: {
      supabaseView: 'call_tracker_events_owner_context',
      plainEnglish:
        'This is the one row-by-row feed for Vercel. Supabase can build it from multiple source tables, but the browser treats every row the same: proof fields plus count booleans.',
      requiredFields: [
        'athlete_name',
        'occurred_at',
        'event_at',
        'tracker_outcome',
        'raw_crm_stage',
        'raw_task_status',
        'raw_event_type',
        'source',
        'appointment_id',
        'live_event_id',
        'booked_event_title',
        'revenue_cents',
        'dedupe_key',
        'active_operator_name',
        'task_assigned_owner',
        'counts_as_dial',
        'counts_as_contact',
        'counts_as_meeting_set',
        'counts_as_post_meeting_outcome',
        'materialization_status',
        'materialization_reason',
        'resolved_owner_name',
        'resolved_owner_source_field',
        'can_materialize_for_active_operator',
        'created_at',
      ],
    },
    summaryHelper: {
      supabaseView: 'call_tracker_summary',
      plainEnglish:
        'This is only a convenience helper for totals. Dials and contacts must mirror the same event-feed booleans.',
      requiredFields: [
        'dials',
        'contacts',
        'meetings_set',
        'meeting_outcomes_total',
        'closed_won',
        'money_earned_cents',
        'voicemail_only',
        'appointments_tracked',
      ],
      deprecatedAliases: {
        total_events: 'Do not display as Dials. Use dials.',
        spoke_with: 'Do not display as Contacts. Use contacts.',
      },
    },
  },
  sourceFamilies: [
    {
      sourceTable: 'call_activity_events',
      rawMeaning: 'Outbound call work and call dispositions from task activity.',
      feedsEventFeedAs: 'raw_event_type = call_activity',
      ownsCounts: ['countsAsDial', 'countsAsContact'],
      mustCarry: [
        'activity_subtype',
        'activity_kind',
        'payload_json.counts_as_dial',
        'payload_json.counts_as_contact',
        'payload_json.counts_as_meeting_set',
        'payload_json.counts_as_post_meeting_outcome',
        'payload_json.materialization_status',
      ],
    },
    {
      sourceTable: 'lifecycle_events',
      rawMeaning: 'Pipeline lifecycle transitions. Meeting Set lives here so it does not disappear after the meeting moves forward.',
      feedsEventFeedAs: 'raw_event_type = lifecycle_meeting_set',
      ownsCounts: ['countsAsDial', 'countsAsContact', 'countsAsMeetingSet'],
      mustCarry: [
        'event_type = meeting_set',
        'payload_json.counts_as_dial',
        'payload_json.counts_as_contact',
        'payload_json.counts_as_meeting_set',
        'payload_json.counts_as_post_meeting_outcome',
        'payload_json.materialization_status',
        'payload_json.owner_context',
      ],
    },
    {
      sourceTable: 'meeting_events',
      deprecatedReadAlias: 'call_events',
      rawMeaning: 'Post-meeting outcomes such as closed won, closed lost, no show, canceled, and reschedule pending.',
      feedsEventFeedAs: 'post-meeting raw_event_type values',
      ownsCounts: ['countsAsPostMeetingOutcome'],
      mustCarry: [
        'raw_event_type = post_meeting_outcome',
        'owner_proof',
        'is_tracked_owner',
        'payload_json.materialization_status',
      ],
    },
  ],
  ownershipContract: {
    plainEnglish:
      'A row can only be trusted for the dashboard when it carries active-operator materialization proof. Vercel should display these fields as proof, not recompute ownership.',
    activeOperator: 'Jerami Singleton',
    requiredEventFields: [
      'materialization_status',
      'materialization_reason',
      'resolved_owner_name',
      'resolved_owner_source_field',
      'resolved_owner_source_value',
      'task_assigned_owner',
      'active_operator_name',
      'can_materialize_for_active_operator',
    ],
    validMaterializationStatusForCounting: 'operator_task',
    sourceOwnerFieldsByFamily: {
      call_activity_events: ['source_owner', 'owner_proof', 'payload_json.materialization_status'],
      lifecycle_events: ['payload_json.owner_context', 'payload_json.materialization_status', 'payload_json.owner_proof'],
      meeting_events: ['source_owner', 'owner_proof', 'is_tracked_owner', 'payload_json.materialization_status'],
    },
  },
  cardBindings: [
    {
      card: 'Total Calls',
      domId: 'todayCalls',
      source: 'eventFeed',
      countRule: 'count rows where counts_as_dial === true',
      plainEnglish: 'How many outbound attempts happened today.',
    },
    {
      card: 'Contacts Made',
      domId: 'todayContacts',
      source: 'eventFeed',
      countRule: 'count rows where counts_as_contact === true',
      plainEnglish: 'How many meaningful contact/disposition outcomes happened today.',
    },
    {
      card: 'Meetings Set',
      domId: 'todayMeetingsSet',
      source: 'eventFeed',
      countRule: 'count rows where counts_as_meeting_set === true',
      plainEnglish: 'How many meetings were set today.',
    },
    {
      card: 'Dials Total',
      domId: 'totalEvents',
      source: 'summaryHelper',
      countRule: 'display call_tracker_summary.dials',
      forbiddenRule: 'Do not display call_tracker_summary.total_events as Dials.',
    },
    {
      card: 'Contacts Total',
      domId: 'spokeWith',
      source: 'summaryHelper',
      countRule: 'display call_tracker_summary.contacts',
      forbiddenRule: 'Do not display call_tracker_summary.spoke_with as Contacts.',
    },
  ],
  domainOutcomeRules: [
    ['call_attempt_1', 'dial', true, false, false, false, 'voicemail', 'Call attempt 1 is an outbound dial but not a contact.'],
    ['call_attempt_2', 'dial', true, false, false, false, 'voicemail', 'Call attempt 2 is an outbound dial but not a contact.'],
    ['call_attempt_3', 'dial', true, false, false, false, 'voicemail', 'Call attempt 3 is an outbound dial but not a contact.'],
    ['unable_to_leave_vm', 'dial', true, false, false, false, 'unable_to_leave_vm', 'Unable to leave voicemail is dial only.'],
    ['spoke_to_not_interested', 'contact', true, true, false, false, 'not_interested', 'Not interested is a real contact outcome, not close lost.'],
    ['spoke_to_athlete_not_parent', 'contact', true, true, false, false, 'spoke_follow_up', 'Reached athlete, not parent, counts as dial and contact.'],
    ['spoke_to_too_young', 'contact', true, true, false, false, 'spoke_follow_up', 'Too young is a contact outcome, not close lost.'],
    ['spoke_to_follow_up', 'contact', true, true, false, false, 'spoke_follow_up', 'Need to follow up is dial and contact.'],
    ['meeting_set', null, true, true, true, false, 'meeting_set', 'Meeting Set counts as dial, contact, and meeting set.'],
    ['closed_won', null, false, false, false, true, 'closed_won', 'Closed won is post-meeting only.'],
    ['closed_lost', null, false, false, false, true, 'closed_lost', 'Closed lost is post-meeting only.'],
    ['reschedule_pending', null, false, false, false, true, 'reschedule_pending', 'Reschedule pending is post-meeting only.'],
    ['no_show', null, false, false, false, true, 'no_show', 'No show is post-meeting only.'],
    ['canceled', null, false, false, false, true, 'canceled', 'Canceled is post-meeting only.'],
  ].map(([domainStatus, activityKind, countsAsDial, countsAsContact, countsAsMeetingSet, countsAsPostMeetingOutcome, trackerOutcome, plainEnglish]) => ({
    domainStatus,
    activityKind,
    countsAsDial,
    countsAsContact,
    countsAsMeetingSet,
    countsAsPostMeetingOutcome,
    trackerOutcome,
    plainEnglish,
  })),
  cronMaterialization: {
    script: 'scripts/materialize-call-tracker-data-contract.mjs',
    packageScript: 'npm run materialize:call-tracker-contract',
    output: 'apps/prospect-web/public/prospect-call-tracker/data-contract.json',
    plainEnglish:
      'Run this with the call tracker cron/sync so Vercel always carries the same contract the domain code expects.',
  },
} as const;
